<?php 
Doo::conf()->LANGUAGES=array(
	'home'=>'メインページ',
	'diary'=>'日記',
	'search'=>'検索',
	'category'=>'カテゴリ',
	'author'=>'作者',
	'links'=>'リンク',
	'tags'=>'タグ',
	'archives'=>'アーカイブ',
	'subscibe'=>'subscibe',
	'postedon'=>'',
	'comment'=>'コメント',
	'nocomment'=>'コメント',
		'reply'=>'リプライ',
	'nickname'=>'ニックネーム',
	'mail'=>'メール',
	'website'=>'ウェッブサイト',
	'required'=>'必要'
	);
?>