<?php 
Doo::conf()->LANGUAGES=array(
	'home'=>'首页',
	'diary'=>'日记',
	'search'=>'搜索',
	'category'=>'分类',
	'author'=>'作者',
	'links'=>'链接',
	'tags'=>'标签',
	'archives'=>'归档',
	'subscibe'=>'订阅',
	'postedon'=>'发布于',
	'comment'=>'评论',
	'nocomment'=>'还没有评论',
	'reply'=>'回复',
	'nickname'=>'昵称',
	'mail'=>'邮箱',
	'website'=>'个人主页',
	'required'=>'必填'
	);
?>